# -*- coding: utf-8 -*-
"""DRIVER LICENCE AMERICAIN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hK93Kl4GcjXOgfr3wuu5T3Tzh6eTWw99
"""

import streamlit as st
import html
import re
import json
from datetime import date, datetime
import hashlib

# --- Fonctions de calcul ---

def calc_expiration(dob: date, issue_date: date):
    """Calcule la date d'expiration pour < 70 ans (5 ans après l'émission, sur l'anniversaire)."""
    exp_year = issue_date.year + 5
    return date(exp_year, dob.month, dob.day)

def calc_dl(last_name: str, dob: date):
    """Simule un numéro de permis (DL) : initiale du nom + 7 chiffres dérivés de la date de naissance."""
    letter = last_name[0].upper()
    dob_str = dob.strftime("%Y%m%d")
    h = hashlib.sha1(dob_str.encode()).hexdigest()
    digits = ''.join([c for c in h if c.isdigit()])[:7]
    return letter + digits

def calc_dd(issue_date: date):
    """Simule un Document Discriminator (DD) basé sur la date d'émission + code interne."""
    code = issue_date.strftime("%m%d%Y")
    suffix = hashlib.md5(code.encode()).hexdigest()[:6]
    return f"{code}{suffix}"

# --- Interface Streamlit ---

st.title("CALCUL DES INFO SUR UN DL CALIFORNIA")

# Formulaire utilisateur
ln = st.text_input("Nom de famille (LN)", "Harms")
fn = st.text_input("Prénom (FN)", "Rosa")
dob_str = st.text_input("Date de naissance (DOB, format YYYY-MM-DD)", "1990-12-31")
iss_str = st.text_input("Date d'émission (ISS, format YYYY-MM-DD)", "2015-09-30")

if st.button("Calculer"):
    dob = datetime.strptime(dob_str, "%Y-%m-%d").date()
    iss = datetime.strptime(iss_str, "%Y-%m-%d").date()

    dl = calc_dl(ln, dob)
    exp = calc_expiration(dob, iss)
    dd = calc_dd(iss)

    # Résultats
    st.subheader("Résultats simulés")
    st.write(f"DL : {dl}")
    st.write(f"EXP : {exp}")
    st.write(f"ISS : {iss}")
    st.write(f"DD : {dd}")
    st.write(f"LN : {ln}")
    st.write(f"FN : {fn}")
    st.write(f"DOB : {dob}")
